name: alive_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  percent_indicator: ^3.4.0
  http: ^1.2.1
  path_provider: ^2.1.3
  file_picker: ^8.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/
